### ISSUE TITLE
Introduce a notion of 'environment'

### ISSUE THREAD

**Issue by inklesspen** [inklesspen/montague#40]
Bundle app config, server config, logging config into a single thing, loadable by name.

**Comment by sontek** [comment]
Yeah, I think something like this:

```
dev:
    application:
        foo: bar

    server:
        biz: baz

    logging:
        qix: quz

prod:
    ....
```

would work best because then when you load it up `pyramid -c app.yaml -e dev serve`

**Comment by inklesspen** [comment]
Unfortunately that is exactly inverted from how PasteDeploy does things, and since backwards compatibility is the only way Montague will get adoption, we're more likely to see something like this:

```
application:
    dev:
        foo: bar
    prod:
         foo: baz
```

Though of course your custom loader is free to rewrite one into the other.
